apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  labels:
    app: go-server-deployment-label
spec:
  selector:
    matchLabels:
      app: go-server-label
  replicas: 1
  template:
    metadata:
      labels:
        app: "go-server-label"
    spec:
      containers:
        - name: go-server-container
          image: "juliucesar/kube-golang:v3"
          env:
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: go-server-env
                  key: NAME

            - name: AGE
              valueFrom:
                configMapKeyRef:
                  name: go-server-env
                  key: AGE
